$axure.loadCurrentPage({
  "url":"nietgelukt.html",
  "generationDate":new Date(1401199224541.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"54efac6d2ef042079165f819918af6f8",
    "type":"Axure:Page",
    "name":"nietgelukt",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b8b46f88a56f4cac85f066ddc9e8bb16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":1170,
              "height":610}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75e6da3ee0864685be2de3a6de10081e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":1170,
                  "height":610}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/nietgelukt/u0.png"}},
{
          "id":"174af993c863468e8295abcc932cd567",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":170},
            "size":{
              "width":420,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6af0df6d93514b9f87fbcc50bed5b2e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":170},
                "size":{
                  "width":420,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/nietgelukt/u2.png"}},
{
          "id":"f3bd731c55e84a9a8b5cc6fb75bc9d07",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":193},
            "size":{
              "width":259,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76ffa713fa3a4512a35d2a106c8aecab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":193},
                "size":{
                  "width":259,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"406b062a78734b2fbf498700dd141aa3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":302.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "b8b46f88a56f4cac85f066ddc9e8bb16":{
      "scriptId":"u0"},
    "75e6da3ee0864685be2de3a6de10081e":{
      "scriptId":"u1"},
    "174af993c863468e8295abcc932cd567":{
      "scriptId":"u2"},
    "6af0df6d93514b9f87fbcc50bed5b2e1":{
      "scriptId":"u3"},
    "f3bd731c55e84a9a8b5cc6fb75bc9d07":{
      "scriptId":"u4"},
    "76ffa713fa3a4512a35d2a106c8aecab":{
      "scriptId":"u5"},
    "406b062a78734b2fbf498700dd141aa3":{
      "scriptId":"u6"}}});