$axure.loadCurrentPage({
  "url":"bekijken.html",
  "generationDate":new Date(1401199224654.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c8da77caf6174498855cffd1c70478cc",
    "type":"Axure:Page",
    "name":"bekijken",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a846962265e142458255e8d8ac376d8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1368,
              "height":656}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fedb579879f4073b693ce91804deaca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1368,
                  "height":656}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/bekijken/u0.png"}},
{
          "id":"780593634f6340b8bb4155aa79a2f3a8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":360,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7d7614b120743e48b48772295362078",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":360,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/bekijken/u2.png"}},
{
          "id":"2778f769bbbc4edb9d3223b8ec10177c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":130},
            "size":{
              "width":520,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c10ed6d580b4803beefd605d5f7f818",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":130},
                "size":{
                  "width":520,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e3bee80153c4c4bb57273a540729096",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":290},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59482c30cd7340119c3f2e11b5a9306c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":290},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/bekijken/u6.png"}},
{
          "id":"226119533a1b492e91b1842621862bfa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":290},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f76f84f06eb490984820a241c4e8508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":290},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/bekijken/u6.png"}},
{
          "id":"c5eb2f567ac74efeab0df65ba0ea1f98",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":290},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e81dc9ce21d4d3db5b49e6573792a0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":290},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/bekijken/u6.png"}},
{
          "id":"7318735b37cc45fbaf1e2464f7db54c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":290},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9bb32182378475a9cc96dd9f2325df9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":290},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/bekijken/u6.png"}},
{
          "id":"73b50a92e66c4f50bb3867f73d6a9b7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":73},
            "size":{
              "width":236,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93e749c49f4b4b73b59421bfc5d32e58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":73},
                "size":{
                  "width":236,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c15dc145c700410289a7f250bec51b1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":280},
            "size":{
              "width":25,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f80a5b2f4724629901192a80c8cf13a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":280},
                "size":{
                  "width":25,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9917bc9fa0d4f94815b52049dc0fa57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":306},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8457a4d3496c4b3bbd7d80eb29329d13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":306},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c95723a9dbb1446fa583f7645dec8bc5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1260,
              "y":620},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "a846962265e142458255e8d8ac376d8a":{
      "scriptId":"u0"},
    "4fedb579879f4073b693ce91804deaca":{
      "scriptId":"u1"},
    "780593634f6340b8bb4155aa79a2f3a8":{
      "scriptId":"u2"},
    "e7d7614b120743e48b48772295362078":{
      "scriptId":"u3"},
    "2778f769bbbc4edb9d3223b8ec10177c":{
      "scriptId":"u4"},
    "5c10ed6d580b4803beefd605d5f7f818":{
      "scriptId":"u5"},
    "9e3bee80153c4c4bb57273a540729096":{
      "scriptId":"u6"},
    "59482c30cd7340119c3f2e11b5a9306c":{
      "scriptId":"u7"},
    "226119533a1b492e91b1842621862bfa":{
      "scriptId":"u8"},
    "1f76f84f06eb490984820a241c4e8508":{
      "scriptId":"u9"},
    "c5eb2f567ac74efeab0df65ba0ea1f98":{
      "scriptId":"u10"},
    "5e81dc9ce21d4d3db5b49e6573792a0a":{
      "scriptId":"u11"},
    "7318735b37cc45fbaf1e2464f7db54c5":{
      "scriptId":"u12"},
    "d9bb32182378475a9cc96dd9f2325df9":{
      "scriptId":"u13"},
    "73b50a92e66c4f50bb3867f73d6a9b7e":{
      "scriptId":"u14"},
    "93e749c49f4b4b73b59421bfc5d32e58":{
      "scriptId":"u15"},
    "c15dc145c700410289a7f250bec51b1b":{
      "scriptId":"u16"},
    "5f80a5b2f4724629901192a80c8cf13a":{
      "scriptId":"u17"},
    "d9917bc9fa0d4f94815b52049dc0fa57":{
      "scriptId":"u18"},
    "8457a4d3496c4b3bbd7d80eb29329d13":{
      "scriptId":"u19"},
    "c95723a9dbb1446fa583f7645dec8bc5":{
      "scriptId":"u20"}}});