$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1401199224201.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"baf3990f5ebb4ae8813a3fab9b3b8243",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"30b3994ee7034852a252b6953451822d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":1310,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f4ac9541de646d9b4d1cc1b2c0063f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":1310,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"7308543f353142a78d7e30b92eef422c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":40,
              "y":578},
            "size":{
              "width":170,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3df32278c4754e8a95efff2ac1ce2672",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":40,
                  "y":578},
                "size":{
                  "width":170,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd6dd9975b934232b196bc5bfaa674df",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":610},
            "size":{
              "width":120,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open laatst gezien in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"laatst_gezien.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d3cf004e0b5e4d0c9e1bcff8d37122bd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1130,
              "y":25},
            "size":{
              "width":160,
              "height":35}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "30b3994ee7034852a252b6953451822d":{
      "scriptId":"u0"},
    "4f4ac9541de646d9b4d1cc1b2c0063f0":{
      "scriptId":"u1"},
    "7308543f353142a78d7e30b92eef422c":{
      "scriptId":"u2"},
    "3df32278c4754e8a95efff2ac1ce2672":{
      "scriptId":"u3"},
    "fd6dd9975b934232b196bc5bfaa674df":{
      "scriptId":"u4"},
    "d3cf004e0b5e4d0c9e1bcff8d37122bd":{
      "scriptId":"u5"}}});